# Generated by Django 3.0.2 on 2020-09-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200910_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertasks',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Task Names'},
        ),
        migrations.AlterField(
            model_name='usertasks',
            name='end_time',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
